spring:
  datasource:
    url: jdbc:mysql://rbassignment.cksffj4rvypk.ap-northeast-2.rds.amazonaws.com:3306/rb?characterEncoding=utf8
    username: root
    password: gudwns12
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 172.31.3.183
    password: gudwns12
    lettuce:
      pool:
        max-active: 10
        max-idle: 10 # 추가 커넥션을 해지하지 않고 풀에서 유휴상태로 유지할 수 있는 최대 연결 수
        min-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update # DB 초기화 전략
    properties:
      hibernate:
        format_sql: true # 콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현
logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.rb.rbassignment
#  mapper-locations: mybatis/mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true