spring:
  datasource:
    url: jdbc:mysql://192.168.101.129:3306/rb?characterEncoding=utf8
    username: khj
    password: gudwns12
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.rb.rbassignment
#  mapper-locations: mybatis/mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true